name: fox
favicon: null
layout_spectrum: 0.1371436109766364
typography_spectrum: 0.8839366973843426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.025182043435052037
  lightness: 0.3058301596902311
  saturation: 0.19467960577458143
  rhythmicContrast: 0.31997874518856406
purpose: []
